[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.buildifier]
command = "buildifier"
includes = ["*.bazel", "*.bzl"]

[formatter.clang-format]
command = "./tools/clang-format"
includes = [".cpp", ".c", ".h", ".hpp"]